package com.poc.esteel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Inventory implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Product Code")
	private java.lang.String productCode;
	@org.kie.api.definition.type.Label(value = "Product Description")
	private java.lang.String productDesc;
	@org.kie.api.definition.type.Label(value = "Quantity")
	private java.lang.Integer quantity;
	@org.kie.api.definition.type.Label(value = "Reason Code")
	private java.lang.String reasonCode;

	public Inventory() {
	}

	public java.lang.String getProductCode() {
		return this.productCode;
	}

	public void setProductCode(java.lang.String productCode) {
		this.productCode = productCode;
	}

	public java.lang.String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(java.lang.String productDesc) {
		this.productDesc = productDesc;
	}

	public java.lang.Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(java.lang.Integer quantity) {
		this.quantity = quantity;
	}

	public java.lang.String getReasonCode() {
		return this.reasonCode;
	}

	public void setReasonCode(java.lang.String reasonCode) {
		this.reasonCode = reasonCode;
	}

	public Inventory(java.lang.String productCode,
			java.lang.String productDesc, java.lang.Integer quantity,
			java.lang.String reasonCode) {
		this.productCode = productCode;
		this.productDesc = productDesc;
		this.quantity = quantity;
		this.reasonCode = reasonCode;
	}

}