package com.poc.esteel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XStore implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Store Name")
	private java.lang.String storeName;

	@org.kie.api.definition.type.Label(value = "Inventory")
	private com.poc.esteel.Inventory inventory;

	public XStore() {
	}

	public java.lang.String getStoreName() {
		return this.storeName;
	}

	public void setStoreName(java.lang.String storeName) {
		this.storeName = storeName;
	}

	public com.poc.esteel.Inventory getInventory() {
		return this.inventory;
	}

	public void setInventory(com.poc.esteel.Inventory inventory) {
		this.inventory = inventory;
	}

	public XStore(java.lang.String storeName, com.poc.esteel.Inventory inventory) {
		this.storeName = storeName;
		this.inventory = inventory;
	}

}